---
- name: Sudo is installed
  ansible.builtin.dnf:
    name: sudo
    state: latest

  vars:
    ansible_python_interpreter: /usr/bin/python3.6
- name: Git is installed
  ansible.builtin.dnf:
    name: git
    state: latest
  vars:
    ansible_python_interpreter: /usr/bin/python3.6
