---
- name: FlowTest tools are installed
  ansible.builtin.dnf:
    name: flowtest
    state: latest

  vars:
    ansible_python_interpreter: /usr/bin/python3.6
- name: tcpreplay is installed
  ansible.builtin.dnf:
    name: tcpreplay
    state: latest
  vars:
    ansible_python_interpreter: /usr/bin/python3.6
